### ISSUE TITLE
gmm.acc_statistics crashes on 32-bits Ubuntu

### ISSUE THREAD

**Issue by pkorshunov** [bioidiap/bob.learn.em#12]
A doctest example in guide.rst (line 147) fails when call to gmm.acc_statistics() is made. The following exception is raised:
RuntimeError: bob.learn.em.GMMMachine - cannot accumulate the statistics: C++ exception caught: 'array dimensions do not match 33 != 3'
Here is the complete buildlog and the reported error when run on 32-bits Ubuntu Trusty:
https://launchpadlibrarian.net/229434954/buildlog_ubuntu-trusty-i386.bob.learn.em_2.0.6-0~ppa5~trusty1_BUILDING.txt.gz

**Comment by tiagofrepereira2012** [comment]
The issue was fixed with the commit 1ff4223
Additional tests were done in 32 bits, all green.

Just waiting the output from Travis-ci to publish the 2.0.7 version.
Thanks for the report.

**Comment by tiagofrepereira2012** [comment]
Package published

https://pypi.python.org/pypi/bob.learn.em/2.0.7
