### ISSUE TITLE
Wrong error return in BOB_CATCH_MEMBER

### ISSUE THREAD

**Issue by siebenkopf** [bioidiap/bob.learn.em#4]
It appears that for some functions, the error return is ``-1`` and not ``NULL``. Usually, those functions return ``int`` and not ``PyObject*``. Particularly, this is the case for the constructors such as:
https://github.com/bioidiap/bob.learn.em/blob/master/bob/learn/em/kmeans_trainer.cpp#L119
and for the setter functions such as:
https://github.com/bioidiap/bob.learn.em/blob/master/bob/learn/em/kmeans_trainer.cpp#L257

This means that the second value in the ``BOB_CATCH_MEMBER`` construct needs to be ``-1`` and not ``NULL`` (aka. ``0``).

@tiagofrepereira2012: could you go through all the files and assure that the error return is correct?

**Comment by tiagofrepereira2012** [comment]
Hey @siebenkopf 

Just to clarify, for the functions that return int I should set  '-1' in the BOB_CATCH_MEMBER, right?
Thanks
